config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :payments, except: :destroy do
    member do
      put :accept
      put :decline
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/stampable.rb
require 'active_support/concern'

module Stampable
  extend ActiveSupport::Concern

  included do
    with_options class_name: 'User' do
      belongs_to :creator
      belongs_to :updater
    end

    before_create :set_creator
    before_update :set_updater
  end

  private

  def set_creator
    self.creator ||= Current.user
    self.updater = creator
  end

  def set_updater
    return unless changes.any?

    self.updater = Current.user
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
  # attribute :request_id, :user_agent, :ip_address
end

app/models/payment.rb
class Payment < ApplicationRecord
  include Stampable
  include Payments::StateMachine

  belongs_to :account, class_name: 'User'

  enum status: %i[initial executed declined]

  validates_presence_of :amount_in_cents, :currency, :purpose, :account_id

  monetize :amount_in_cents, as: :amount, with_currency: ->(payment) { payment.currency }
  has_paper_trail ignore: [:id, :created_at, :updated_at, :updater_id, :creator_id, :lock_version]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[customer admin]

  validates_uniqueness_of :email, case_sensitivity: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
  before_action :authenticate_user!

  add_flash_types :notice, :error, :success

  before_action :set_current_user, if: :user_signed_in?
  before_action :set_paper_trail_whodunnit

  rescue_from ActiveRecord::StaleObjectError, with: :stale_object
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def set_current_user
    Current.user = current_user
  end

  def stale_object
    flash[:error] = t('optimistic_locked')
    redirect_back(fallback_location: root_path)
  end

  def user_not_authorized
    flash[:error] = t('not_authorized')
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include Pundit
  before_action :payment, only: %i[show edit update accept decline]
  append_before_action :pundit_authorize

  def index
    @payments = Payment.all.includes(:creator, :updater, :account).order(:created_at)
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    if @payment.save
      redirect_to :payments
    else
      render :new
    end
  end

  def update
    @payment.assign_attributes(payment_params)
    if @payment.save
      redirect_to :payments
    else
      render :edit
    end
  end

  def show; end
  def edit; end

  def accept
    if @payment.accept!
      flash[:success] = 'The payment has been accepted'
    else
      flash[:error] = @payment.errors.full_messages
    end
    redirect_to :payments
  end

  def decline
    if @payment.decline!
      flash[:success] = 'The payment has been declined'
    else
      flash[:error] = @payment.errors.full_messages
    end
    redirect_to :payments
  end

  private

  def payment_params
    params.require(:payment).permit(:amount_in_cents, :currency, :account_id, :purpose, :lock_version)
  end

  def payment
    @payment ||= Payment.find(params[:id])
  end

  def pundit_authorize
    authorize [@payment || Payment]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_flash_messages
    out         = []
    flash_types = { 'success' => 'alert-success', 'error' => 'alert-danger', 'notice' => 'alert-info' }
    flash.delete('timedout')
    flash.each do |key, flash_attributes|
      value = flash_attributes
      if flash_attributes.is_a? Hash
        value = flash_attributes['message']
        button = flash_attributes['button']
      end

      content = value
      if value.is_a? Array
        content = '<div class="list">'
        value.each do |message|
          content += "<div class=\"item\">#{message}</div>"
        end
        content += '</div>'
      end

      class_flash = flash_types[key] || 'alert-danger'
      out << "<div class=\"alert #{class_flash}\" role=\"alert\">"
      out << '<button type="button" class="close" aria-label="Close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>'
      out << "<div class='content'>#{content}</div>"
      out << "<a class=\"flash_button\" href=\"#{button['link']}\"> #{button['message']}</a>" if button.present?
      out << '</div>'
    end
    out.join('').html_safe
  end

  def payments_changes(payment, version)
    changes = version.changeset
    amount_changes = changes.delete('amount_in_cents') || []
    account_changes = changes.delete('account_id') || []

    content_tag('ul') do
      content = []
      if amount_changes.any?
        content << content_tag('li') do
          [content_tag('h6', 'Amount in cents: '),
          amount_changes.map do |amount|
            humanized_money_with_symbol(Money.new(amount, version.changeset['currency']&.last || payment.currency))
          end.join(' -> ')].join.html_safe
        end
      end
      if account_changes.any?
        content << content_tag('li') do
          [content_tag('h6', 'Account: '),
          account_changes.map { |id| User.find_by(id: id)&.email }.compact.join(' -> ')].join.html_safe
        end
      end
      version.changeset.each do |attr, set|
        content << content_tag('li') do
          [content_tag('h6', "#{attr}: "),
          set.compact.join(' -> ')].join.html_safe
        end
      end

      content.join.html_safe
    end
  end
end

app/views/home/index.html.slim
.row.justify-content-md-center
  .col.col-md-auto
    = t('greeting', user: current_user.email)
  - if current_user.admin?
    .col.col-md-2
      = link_to t('nav.payments'), :payments

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:page_title) || 'Fintech'
    meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0' name='viewport'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&amp;subset=latin-ext" rel="stylesheet"
    = javascript_include_tag 'application'

  body
    div#app
      - if user_signed_in?
        .container
          .row.justify-content-md-start.mx-5
            .col.col-md-8
              = link_to 'Logout', destroy_user_session_path, method: :delete
      .jumbotron
        = render_flash_messages
        = yield

app/views/payments/_form.html.slim
= simple_form_for(@payment) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :lock_version
    = f.input :amount_in_cents
    = f.input :currency, collection: Money::Currency.table
    = f.input :purpose
    = f.input :account_id, collection: User.customer.pluck(:id, :email),
                           label_method: :second, value_method: :first,
                           label: t('payments.form.account'), prompt: :translate

  .form-actions.mb-5
    = f.button :submit, class: 'btn btn-primary'

app/views/payments/edit.html.slim
.container
  h1 Editing payment

  == render 'form'

  => link_to 'Show', @payment
  '|
  =< link_to 'Back', payments_path

app/views/payments/index.html.slim
- content_for(:page_title)
  = "Fintech | #{t('titles.payments')}"
.row.justify-content-md-center
  .col.col-md-12
    - if @payments.any?
      .list-group.mb-2
        .list-group-item
          .row.justify-content-between
            h5.col.col-md-1 = '#'
            h5.col.col-md-2 = "Account"
            h5.col.col-md-2 = "Amount"
            h5.col.col-md-2 = "Purpose"
            h5.col.col-md-1 = "Status"
            h5.col.col-md-2 = "Last changes by"
            h5.col.col-md-2.text-right
      .list-group
        - @payments.each.with_index(1) do |payment, index|
          .list-group-item class=([('bg-info' if payment.executed?), ('bg-secondary' if payment.declined?)])
            .row.justify-content-between
              .col.col-md-1 = "#{index}."
              .col.col-md-2 = payment.account.email
              .col.col-md-2 = humanized_money_with_symbol(payment.amount)
              .col.col-md-2 = payment.purpose
              .col.col-md-1 = payment.status
              .col.col-md-2 = payment.updater.email
              .col.col-md-2.text-right
                  .dropdown
                    button.btn.btn-secondary.dropdown-toggle[type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                      = t('actions')
                    .dropdown-menu[aria-labelledby="dropdownMenu2"]
                      = link_to payment_path(payment) do
                        .dropdown-item[type="button"] = t('view')
                      - unless payment.declined? || payment.executed?
                        = link_to edit_payment_path(payment) do
                          .dropdown-item[type="button"] = t('edit')
                      - if payment.may_accept?
                        = link_to accept_payment_path(payment, payment: { lock_version: payment.lock_version }), method: :put do
                          .dropdown-item[type="button"] = t('accept')
                      - if payment.may_decline?
                        = link_to decline_payment_path(payment, payment: { lock_version: payment.lock_version }), method: :put do
                          .dropdown-item[type="button"] = t('decline')

    - else
      h3.title = t('nothing_found')

    .row.mt-5
      .col.col-md-auto
        = link_to new_payment_path do
          button.btn.btn-primary[type="button"] = t('add_payments')

app/views/payments/new.html.slim
.container
  h1 New payment

  == render 'form'

  = link_to 'Back', payments_path

app/views/payments/show.html.slim
p
  strong Account:
  span.ml-1
    = @payment.account.email

p
  strong Purpose:
  span.ml-1
    = @payment.purpose

p
  strong Amount in cents:
  span.ml-1
    = @payment.amount_in_cents
p
  strong Currency:
  span.ml-1
    = @payment.currency

=> link_to 'Edit', edit_payment_path(@payment)
'|
=< link_to 'Back', payments_path

h3.mx-5 = 'History'

.row.justify-content-between.mt-5
  .col.col-md-12
    .list-group.mb-2
      - @payment.versions.each do |version|
        .list-group-item
          = "#{version.created_at} #{User.find_by(id: version.version_author)&.email} #{version.event}"
          = payments_changes(@payment, version).html_safe